[package]
name = "events-rs"
version = "0.1.0"
edition = "2021"
publish = ["rsproxy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "^0.3"
log = "^0.4"
errno = "0.3.0"

[target.'cfg(target_family = "unix")'.dependencies]
libc = "^0.2"
